dist: xenial
sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
install:
  - pip install mypy
  - pip install coveralls
script:
  - mypy -p bdemeta -m tests.cmake_parser
  - coverage run -m unittest
after_success:
  - coveralls
